services:
  - type: web
    name: muebleria-gm
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node --experimental-strip-types src/server.ts
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PORT
        value: 3000